### ISSUE TITLE
是否应处理一下Promise对象被作为消息的情况

### ISSUE THREAD

**Issue by ZM-J** [XasYer/ws-plugin#1]
如图

![image](https://github.com/xiaoye12123/ws-plugin/assets/21689514/56f11015-3dc7-4e94-a639-e8a921a87f0a)

![image](https://github.com/xiaoye12123/ws-plugin/assets/21689514/a20044c2-b843-4e91-b047-ef7c28c05a7a)

还是说需要在开发插件时不能做异步请求？

**Comment by xiaoye12123** [comment]
https://icqqjs.github.io/icqq/docs/variables/segment.html
望周知

**Comment by kldhsh123** [comment]
> https://icqqjs.github.io/icqq/docs/variables/segment.html 望周知

emmm链接404了
