### ISSUE TITLE
青龙面板使用gocq推送报错

### ISSUE THREAD

**Issue by Fahaxikiii** [XasYer/ws-plugin#15]
![Screenshot_2024-02-07-17-27-32-401_com microsoft emmx](https://github.com/XasYer/ws-plugin/assets/93320886/d32da978-c768-497c-bcd3-7c0f626424ee)

**Comment by Fahaxikiii** [comment]
![Screenshot_2024-02-07-17-32-30-607_com server auditor ssh client-edit](https://github.com/XasYer/ws-plugin/assets/93320886/666fe464-11e5-4700-a4c4-1bef426b6580)

**Comment by XasYer** [comment]
是http吗

**Comment by Fahaxikiii** [comment]
直接在青龙面板的配置文件中添加推送配置部分脚本可以正常推送，不过大多数脚本依旧会报错
![image](https://github.com/XasYer/ws-plugin/assets/93320886/9b835a28-1b1a-427f-83e7-573d4402cd57)
![image](https://github.com/XasYer/ws-plugin/assets/93320886/5a5e5fb3-e753-4f8e-8a5f-362c3eeacdcb)

**Comment by XasYer** [comment]
更新一下看看

**Comment by Fahaxikiii** [comment]
> 更新一下看看

好的

**Comment by Fahaxikiii** [comment]
> 更新一下看看

好了好了。感谢大佬！
